spring:
  application:
    name: catalog-service
  data:
    mongodb:
      host: localhost
      username: catalogservice
      password: catalogservice
      authentication-database: admin
      database: catalogservice
  mail:
    username: eglrgroup9@gmail.com
    password: z5i59QRJLwpAyxT
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
application:
  serverURL: localhost:8081
  jwt:
    jwtSecret: that_depends_a_good_deal_on_where_you_want_to_get_to_then_it_doesnt_much_matter_which_way_you_go
    jwtExpirationMs: 1800000
    jwtHeader: Authorization
    jwtHeaderStart: Bearer

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}

server:
  port: 8081

