package it.polito.wa2.orderservice.common

enum class StateMachineEvents {
    RESERVE_PRODUCTS,
    RESERVE_PRODUCTS_OK,
    RESERVE_PRODUCTS_FAILED,
    PAYMENT_REQUEST,
    PAYMENT_REQUEST_OK,
    PAYMENT_REQUEST_FAILED,
    ABORT_PRODUCTS_RESERVATION,
    ABORT_PRODUCTS_RESERVATION_OK,
    ABORT_PRODUCTS_RESERVATION_FAILED,
    ABORT_PAYMENT_REQUEST,
    ABORT_PAYMENT_REQUEST_OK,
    ABORT_PAYMENT_REQUEST_FAILED,
}